on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_pull:
    # we use jobs in a matrix.
    # the OS to be used for the test is taken from the current matrix element
    runs-on: ${{ matrix.os }}
    strategy:
      # we want to avoid to stop all the tests the first time that one of them gets an error
      fail-fast: false
      matrix:
        include:
        #here we set up the various matrix elements
        #the entries in each matrix element are just variables, not keywords, with (hopefully) self-explaining names
        # 1st matrix element, default compiler at FIAS
        - os: ubuntu-18.04
          site: "fias"
          packages_to_add: "libboost-all-dev g++-5 doxygen-latex graphviz libgsl-dev"
          c_compiler_to_use: "gcc-5"
          cxx_compiler_to_use: "g++-5"
        # 2nd matrix element, recent LTS Ubuntu distribution with gcc
        - os: ubuntu-20.04
          site: "linux-default-gcc"
          packages_to_add: "libboost-all-dev doxygen-latex graphviz libgsl-dev"
          c_compiler_to_use: "gcc"
          cxx_compiler_to_use: "g++"
        # 3rd matrix element, recent LTS Ubuntu distribution with clang
        - os: ubuntu-20.04
          site: "linux-default-clang"
          packages_to_add: "libboost-all-dev libgsl-dev"
          c_compiler_to_use: "clang"
          cxx_compiler_to_use: "clang++"
        # 4th matrix element, osx 11 with clang
        - os: macos-11
          site: "mac"
          packages_to_add: "boost gsl"
          c_compiler_to_use: "clang"
          cxx_compiler_to_use: "clang++"
    steps:
    # this is an action provided by GitHub to checkout the repository
    - uses: actions/checkout@v2
    # this is an other GitHub action to properly setup the python environment (needed for cmake-format installation)
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    # we set the name of the step, collecting all the tests in just one step
    - name: code_check
    # we set some environment variables for the specific OS version
      env:
        CC: ${{ matrix.c_compiler_to_use }}
        CXX: ${{ matrix.cxx_compiler_to_use }}
        OS_NAME: ${{ matrix.os }}
        SITE: ${{ matrix.site }}
      # we run the step. We recall that in YAML the pipe symbol "|" means that the follwing lines, including newlines, are interpreted literally
      run: |
        # which version of cmake is used
        cmake --version
        # we set the smash root directory
        export SMASH_ROOT=$PWD
        # we install the missing packages
        if [ $SITE == "mac" ]; then
            brew install ${{ matrix.packages_to_add }}
        else
            sudo apt-get install ${{ matrix.packages_to_add }} -y
        fi
        # we download and install Pythia
        wget https://pythia.org/download/pythia83/pythia8307.tgz && tar xf pythia8307.tgz && rm pythia8307.tgz && cd pythia8307
        ./configure --cxx-common='-std=c++11 -march=native -mfpmath=sse -O3 -fPIC' && make -j$(nproc) && cd ..
        # we download and unpack clang
        if [ $SITE == "mac" ]; then curl -# -o clang6_0_0.tar.xz https://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz;
        else curl -# -o clang6_0_0.tar.xz https://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz; fi &&
        mkdir clang6_0_0 && tar -xf clang6_0_0.tar.xz -C clang6_0_0 --strip-components=1
        # we install cmake-format in a dedicated directory and adjust environment
        mkdir $SMASH_ROOT/python-tools && pip install --target $SMASH_ROOT/python-tools cmakelang==0.6.13
        export PYTHONPATH=$SMASH_ROOT/python-tools:$PYTHONPATH
        # we get eigen
        wget http://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz && tar -xf eigen-3.4.0.tar.gz -C $HOME
        # we get cpplint
        wget https://raw.githubusercontent.com/cpplint/cpplint/develop/cpplint.py && chmod +x cpplint.py && mkdir -p $HOME/bin && mv cpplint.py $HOME/bin
        export PATH=$HOME/bin:$PATH
        # now we build SMASH
        cd $SMASH_ROOT && mkdir build && cd build
        cmake .. -DPythia_CONFIG_EXECUTABLE=$SMASH_ROOT/pythia8307/bin/pythia8-config -DCMAKE_INSTALL_PREFIX=$HOME/eigen-3.4.0/
        make -j$(nproc)
        # we check the building of the documentation for a specific case
        if [ $SITE == "fias" ]; then make undocumented_test && make user; fi
        # we check the correct formatting of the code with clang
        PATH=$SMASH_ROOT/clang6_0_0/bin/:$PATH ./../bin/codebase-format-helper.bash C++ -t
        PATH=$SMASH_ROOT/python-tools/bin/:$PATH ./../bin/codebase-format-helper.bash CMake -t
        # we run the tests
        CTEST_OUTPUT_ON_FAILURE=1 ctest -j$(nproc)
